#!/bin/sh
#
# A git pre-commit hook script to make sure no new shellcheck warnings are
# introduced.

# Redirect output to stderr.
exec 1>&2

if [ ! -e /usr/bin/shellcheck ]; then
	cat <<EOF
Error: Commit aborted in pre-commit hook due to missing shellcheck.

Please install shellcheck to use this hook.
EOF
	exit 1
fi

if ! shellcheck -S warning umpf; then
	cat <<EOF

Error: Commit aborted in pre-commit hook due to shellcheck warnings.

Please make sure "shellcheck -S warning umpf" reports no warnings before trying to commit.
EOF
	exit 1
fi
