#!/bin/sh
#
# Test merging topic branches with "umpf merge".
#

umpf merge a
umpf merge b

umpf show --identical --base=base --name=name > series.merge

diff -u ${TEST_DIR}/series-merge.ref series.merge
