#!/bin/bash
#
# Test creating a Yocto compatible patchset with "umpf format-patch --bb".
#

umpf format-patch umpf-tag --bb --patchdir=patches

diff -u ${TEST_DIR}/series-format-patch-bb.ref patches/series.inc
